name: stratigraph

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - matplotlib=3.7.1
  - pyqt=5.15.7
  - pandas
  - jupyterlab
  - mayavi
  - scipy
  - scikit-image
  - scikit-learn
  - Pillow
  - shapely
  - tqdm
  - pip